### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by asterite** [instedd/mobile-gateway#1]
Improve error messages displayed to the user when mobile network delivery fails, or internet connectivity is lost

**Comment by spalladino** [comment]
Avoid java errors such as `Fatal error: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)`

**Comment by spalladino** [comment]
Unexpected QstClientErrors are displayed as "Error connecting to messaging server", and unexpected throwables are displayed as "Unexpected fatal error". The internals of the error can be seen by long-clicking on the entry. Non-errors have no long-click event.

![screen shot 2016-04-12 at 5 46 58 pm](https://cloud.githubusercontent.com/assets/429604/14475893/d8ae95a2-00da-11e6-8c37-cc3dc0ff7925.png)

**Comment by mmuller** [comment]
Working as expected.
