### ISSUE TITLE
Improve failed messages retries policy

### ISSUE THREAD

**Issue by asterite** [instedd/mobile-gateway#3]
Ensure message sending retries are performed at reasonable intervals, and only when connectivity is available

**Comment by spalladino** [comment]
Upon a message failure, increase the date of the next retry and reenque, performing exponential backoff per message with a max age. When max age is reached, the message is deleted from the LGW and reported to Nuntium as failed.

If the user manually chooses to retry a message (or all of them), remove all retries count and treat it as a new message, retrying it immediately.

Check if it is possible to distinguish the cause of a failed message, such as invalid number, and do not retry those messages. If the error is generic, assume all errors are temporary.
- Max age: 7d, configurable between 1-30
- Retries: 1 min - 1 min - 2 min - 5 min - 15 min - 30 min - 1h - 3h - 3h ...

**Comment by spalladino** [comment]
As a NTH, consider a micro-retries policy. If a message fails, pause the delivery of messages from the queue, retry a few seconds later, repeat one more time, and only then move the message to the "retries" queue. See #7.

**Comment by pmallol** [comment]
Ok in version 2.2
