### ISSUE TITLE
Confirm before clearing configuration

### ISSUE THREAD

**Issue by spalladino** [instedd/mobile-gateway#9]
Request user confirmation before clearing current config.

**Comment by spalladino** [comment]
<img width="671" alt="screen shot 2016-04-21 at 1 31 08 pm" src="https://cloud.githubusercontent.com/assets/429604/14716888/617240e6-07c5-11e6-83f9-90360934ef84.png">

**Comment by mmuller** [comment]
Now a reset confirmation is displayed as expected.
